### ISSUE TITLE
DEGs output csv format

### ISSUE THREAD

**Issue by wangjiawen2013** [cboix/admultiregion_analysis#1]
Hi,
Here is the DEGs I downloaded from https://compbio.mit.edu/ad_multiregion/
what does cogn_global_lv  and cogng_random_slope mean ? The logFC between them differs a lot, which one should I use ?

![image](https://github.com/user-attachments/assets/9ec2de33-a5d3-495f-8232-6a65c139bd77)
![image](https://github.com/user-attachments/assets/175de756-b644-4dfb-8a94-91f1cd058212)

**Comment by cboix** [comment]
Hi,

We based the cognitive resilience scores on two variables, global cognitive function (cogn_global_lv) and rate of decline of global cognitive function (cogng_random_slope). Global cognitive function is used for the CR scores and the slope variable is used for the CDR scores. The two variables have very different dynamic ranges and so the logFC should reflect that, but it shouldn't be a reason to use one set of results over the other. 

In this case, it looks like you're looking at the DEG results for cognitive resilience under the "_corrected" folders. These use the cognition variables as-is (instead of calculating the CR and CDR scores) and the regression model corrects for AD pathology by adding that variable (gpath, nft, plaq_d, or tangles) as an additional term.

We've added a readme to explain the DEGs at https://personal.broadinstitute.org/cboix/multiregion/DEGs/CR_DEGs/README.txt and you can find descriptions of the ROSMAP variables at https://www.radc.rush.edu/docs/var/variables.htm under "Cognition".

**Comment by lqplqplqp299** [comment]
Hi, I am a student studying medical machine learning, your work is very great, I admire you！！ I have been studying your work recently, but I don't quite understand how the code works, how should I match the exposed data with the code correctly? If possible, please give some tips or suggestions, which will be more helpful to my understanding of the article, thank you!

**Comment by lqplqplqp299** [comment]
> Hi, Here is the DEGs I downloaded from https://compbio.mit.edu/ad_multiregion/ what does cogn_global_lv and cogng_random_slope mean ? The logFC between them differs a lot, which one should I use ?
> 
> ![image](https://private-user-images.githubusercontent.com/29703450/354058775-9ec2de33-a5d3-495f-8232-6a65c139bd77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODE4MDYsIm5iZiI6MTczMTM4MTUwNiwicGF0aCI6Ii8yOTcwMzQ1MC8zNTQwNTg3NzUtOWVjMmRlMzMtYTVkMy00OTVmLTgyMzItNmE2NWMxMzliZDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAzMTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlOGJhYjNkMDc3MDdhODVmMjY2OWEyOWUxZDdkNjdlOTAzOWUxNjhhMzI5Y2I1ODdmMGUyOGI5YTU2ODkxNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f7NI9pblpRiYPDacSlNpi_zRqIhfeX2_NjYNoOgae9Y) ![image](https://private-user-images.githubusercontent.com/29703450/354059235-175de756-b644-4dfb-8a94-91f1cd058212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODE4MDYsIm5iZiI6MTczMTM4MTUwNiwicGF0aCI6Ii8yOTcwMzQ1MC8zNTQwNTkyMzUtMTc1ZGU3NTYtYjY0NC00ZGZiLThhOTQtOTFmMWNkMDU4MjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAzMTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNTA0MDU1NzUzNDA5NGU2NWRjYjVmMjU2NmFjMDQ4Yzk1Yjc1MjkyNjQyNGI0Y2Y4MTJkZDdlZmI0ZmJhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h73P9BLIgD6-btiyGjiw-G0gZko4FpSvwtFMvoVAP68)

Hello，Is your method reproduced successfully?
